# Generated by Django 3.2.9 on 2021-12-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_yourmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
